name: "TeamHunters"
main: "io.getcoffee.hunters.Hunters"
author: "oldgalileo"
version: "0.2.3"
api-version: "1.16"

commands:
  hunt_start:
    permission: op
    aliases: ["hstart"]
  hunt_pause:
    permission: op
    aliases: ["hpause"]